POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZvaWQucG9pbnRlckBnbWFpbC5jb20iLCJleHAiOjE3MjI0MjY4MDMsInVzZXJJZCI6MX0.8EVv_zqMAPyMSYdOpHx0XPQbarbJ2F4Zel0qVhS1vXQ

{
	"name": "Test Event",
	"description": "Test Description",
	"location": "New York",
	"dateTime": "2024-01-01T13:30:00.000Z"
}