POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZvaWQucG9pbnRlckBnbWFpbC5jb20iLCJleHAiOjE3MjI0Mjg2NjIsInVzZXJJZCI6MX0.h6HiYqS5E-65GF9Ysk4rcc9K9ULhShCqJcKL0ScRStY

{
	"name": "Test Event",
	"description": "Test Description",
	"location": "New York",
	"dateTime": "2024-01-01T13:30:00.000Z"
}