POST http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZvaWQucG9pbnRlckBnbWFpbC5jb20iLCJleHAiOjE3MjI0OTc3OTMsInVzZXJJZCI6MX0.0sDckfOX6RMsdUkIxuwQVkXacNFWWuosV-qiwsNmX6c